import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// Shared cn() utility — mirrors the one generated by shadcn/ui
// Kept here so both web and mobile (via NativeWind) can import it.
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
